In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver

In [2]:
browser = webdriver.Chrome(executable_path='chromedriver.exe')

In [3]:
city_dict= {'Paris': 568836.0,
 'Stockholm': 61121.0,
 'London': 757656.0,
 'Berlin': 136518.0,
 'Munich': 69446.0,
 'Oporto': 66134.0,
 'Milan': 356036.0,
 'Bratislava': 15116.0,
 'Vienna': 92674.0,
 'Rome': 585930.0,
 'Barcelona': 343737.0,
 'Madrid': 298024.0,
 'Dublin': 100585.0,
 'Brussels': 90397.0,
 'Zurich': 40256.0,
 'Warsaw': 44644.0,
 'Budapest': 121382.0,
 'Copenhagen': 57686.0,
 'Amsterdam': 153559.0,
 'Lyon': 74501.0,
 'Hamburg': 43084.0,
 'Lisbon': 156510.0,
 'Prague': 164318.0,
 'Oslo': 35372.0,
 'Helsinki': 22044.0,
 'Edinburgh': 134954.0,
 'Geneva': 28948.0,
 'Ljubljana': 13141.0,
 'Athens': 59326.0,
 'Luxembourg': 16613.0,
 'Krakow': 50959.0}

In [4]:
city_list = list()
population_dict = dict()
density_dict = dict()
area_dict = dict()
for city in city_dict.keys():
    population_dict[city]=0
    density_dict[city]=0
    area_dict[city]=0
    city_list.append(city)
area_dict

{'Paris': 0,
 'Stockholm': 0,
 'London': 0,
 'Berlin': 0,
 'Munich': 0,
 'Oporto': 0,
 'Milan': 0,
 'Bratislava': 0,
 'Vienna': 0,
 'Rome': 0,
 'Barcelona': 0,
 'Madrid': 0,
 'Dublin': 0,
 'Brussels': 0,
 'Zurich': 0,
 'Warsaw': 0,
 'Budapest': 0,
 'Copenhagen': 0,
 'Amsterdam': 0,
 'Lyon': 0,
 'Hamburg': 0,
 'Lisbon': 0,
 'Prague': 0,
 'Oslo': 0,
 'Helsinki': 0,
 'Edinburgh': 0,
 'Geneva': 0,
 'Ljubljana': 0,
 'Athens': 0,
 'Luxembourg': 0,
 'Krakow': 0}

In [5]:
url_list = list()
for element in city_list:
    if element == 'Luxembourg':
         url_list.append('https://en.wikipedia.org/wiki/Luxembourg_City')
    else:
        url_list.append('https://en.wikipedia.org/wiki/'+str(element))
url_list

['https://en.wikipedia.org/wiki/Paris',
 'https://en.wikipedia.org/wiki/Stockholm',
 'https://en.wikipedia.org/wiki/London',
 'https://en.wikipedia.org/wiki/Berlin',
 'https://en.wikipedia.org/wiki/Munich',
 'https://en.wikipedia.org/wiki/Oporto',
 'https://en.wikipedia.org/wiki/Milan',
 'https://en.wikipedia.org/wiki/Bratislava',
 'https://en.wikipedia.org/wiki/Vienna',
 'https://en.wikipedia.org/wiki/Rome',
 'https://en.wikipedia.org/wiki/Barcelona',
 'https://en.wikipedia.org/wiki/Madrid',
 'https://en.wikipedia.org/wiki/Dublin',
 'https://en.wikipedia.org/wiki/Brussels',
 'https://en.wikipedia.org/wiki/Zurich',
 'https://en.wikipedia.org/wiki/Warsaw',
 'https://en.wikipedia.org/wiki/Budapest',
 'https://en.wikipedia.org/wiki/Copenhagen',
 'https://en.wikipedia.org/wiki/Amsterdam',
 'https://en.wikipedia.org/wiki/Lyon',
 'https://en.wikipedia.org/wiki/Hamburg',
 'https://en.wikipedia.org/wiki/Lisbon',
 'https://en.wikipedia.org/wiki/Prague',
 'https://en.wikipedia.org/wiki/Oslo',
 'https://en.wikipedia.org/wiki/Helsinki',
 'https://en.wikipedia.org/wiki/Edinburgh',
 'https://en.wikipedia.org/wiki/Geneva',
 'https://en.wikipedia.org/wiki/Ljubljana',
 'https://en.wikipedia.org/wiki/Athens',
 'https://en.wikipedia.org/wiki/Luxembourg_City',
 'https://en.wikipedia.org/wiki/Krakow']

In [6]:
my_table_list = list()
rows_list = list()
for url in url_list:
    browser.get(url)
    required_HTML = browser.page_source
    soup = BeautifulSoup(required_HTML, 'html5lib')
    table = soup.findChildren('table')
    my_table = table[0]
    my_table_list.append(table[0])
    rows = my_table.findChildren(['th', 'tr'])
    rows_list.append(rows)

In [7]:
i = 0
k = 0
parse_list = list()
for rows in rows_list:
    for row in rows:
        cells1 = row.findChildren('th')
        cells2 = row.findChildren('td')
        for cell in cells1:
            value1 = cell.text
            if ('urban' in value1.lower())or('capital city' in value1.lower())or('population' in value1.lower())or('metropolitan city' in value1.lower()):
                k = 1
                parse_list.append([city_list[i],value1,'type 1',k])
            
        for cell in cells2:
            if k>0:
                value2 = cell.text
                parse_list.append([city_list[i],value2,'type 2',k])
                k += -1
    i += 1
parse_list

[['Paris', '\xa0•\xa0Urban\xa0(2020)', 'type 1', 1],
 ['Paris', '2,853.5\xa0km2 (1,101.7\xa0sq\xa0mi)', 'type 2', 1],
 ['Paris', 'Population\xa0(Jan.\xa02018)[1]', 'type 1', 1],
 ['Paris', '2,175,601', 'type 2', 1],
 ['Paris', '\xa0•\xa0Urban\xa0(Jan.\xa02017[2])', 'type 1', 1],
 ['Paris', '10,785,092', 'type 2', 1],
 ['Paris', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Paris', '3,800/km2 (9,800/sq\xa0mi)', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Stockholm', '188\xa0km2 (73\xa0sq\xa0mi)', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Urban', 'type 1', 1],
 ['Stockholm', '381.63\xa0km2 (147.35\xa0sq\xa0mi)', 'type 2', 1],
 ['Stockholm', 'Population\xa0(31 December 2020)[3][4][5]', 'type 1', 1],
 ['Stockholm', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Stockholm', '975,551', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Urban[6]', 'type 1', 1],
 ['Stockholm', '1,605,030', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Stockholm', '4,200/km2 (11,000/sq\xa0mi)', 'type 2', 1],
 ['London', '\xa0•\xa0Urban', 'type 1', 1],
 ['London', '1,737.9\xa0km2 (671.0\xa0sq\xa0mi)', 'type 2', 1],
 ['London', 'Population\xa0(2018)[5]', 'type 1', 1],
 ['London', '8,961,989[1]', 'type 2', 1],
 ['London', '\xa0•\xa0Urban', 'type 1', 1],
 ['London', '9,787,426', 'type 2', 1],
 ['Berlin', 'Population\xa0(31 December 2019)[2]', 'type 1', 1],
 ['Berlin', '3,769,495', 'type 2', 1],
 ['Berlin', '\xa0•\xa0Urban[3]', 'type 1', 1],
 ['Berlin', '4,473,100', 'type 2', 1],
 ['Munich', 'Population\xa0(2019-12-31)[2]', 'type 1', 1],
 ['Munich', '1,484,226', 'type 2', 1],
 ['Munich', '\xa0•\xa0Urban', 'type 1', 1],
 ['Munich', '2,606,021', 'type 2', 1],
 ['Oporto', 'Population', 'type 1', 1],
 ['Oporto', '287,591', 'type 2', 1],
 ['Milan', 'Population\xa0(February 28, 2020)[1]', 'type 1', 1],
 ['Milan', '1,399,860', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Bratislava', '367.584\xa0km2 (141.925\xa0sq\xa0mi)', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Urban', 'type 1', 1],
 ['Bratislava', '853.15\xa0km2 (329.40\xa0sq\xa0mi)', 'type 2', 1],
 ['Bratislava', 'Population\xa0(2019-12-31[1])', 'type 1', 1],
 ['Bratislava', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Bratislava', '437,726', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Urban', 'type 1', 1],
 ['Bratislava', '563,682', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Bratislava', '661/km2 (1,710/sq\xa0mi)', 'type 2', 1],
 ['Vienna', '\xa0•\xa0Capital city and state', 'type 1', 1],
 ['Vienna', '414.78\xa0km2 (160.15\xa0sq\xa0mi)', 'type 2', 1],
 ['Vienna', 'Population', 'type 1', 1],
 ['Vienna', '\xa0•\xa0Capital city and state', 'type 1', 1],
 ['Vienna', '', 'type 2', 1],
 ['Vienna', '\xa0•\xa0Urban', 'type 1', 1],
 ['Vienna', '1,911,191 (01−01−20)', 'type 2', 1],
 ['Rome', 'Metropolitan city', 'type 1', 1],
 ['Rome', 'Rome', 'type 2', 1],
 ['Rome', 'Population\xa0(31 December 2019)', 'type 1', 1],
 ['Rome', '1st in Italy (3rd in the EU)', 'type 2', 1],
 ['Rome', '\xa0•\xa0Metropolitan City', 'type 1', 1],
 ['Rome', '4,342,212[2]', 'type 2', 1],
 ['Barcelona', 'Population\xa0(2018)[5]', 'type 1', 1],
 ['Barcelona', '1,620,343', 'type 2', 1],
 ['Barcelona', '\xa0•\xa0Urban', 'type 1', 1],
 ['Barcelona', '4,840,000[3]', 'type 2', 1],
 ['Madrid', '\xa0•\xa0capital city and municipality', 'type 1', 1],
 ['Madrid', '604.31\xa0km2 (233.33\xa0sq\xa0mi)', 'type 2', 1],
 ['Madrid', 'Population\xa0(2018)[4]', 'type 1', 1],
 ['Madrid', '\xa0•\xa0capital city and municipality', 'type 1', 1],
 ['Madrid', '3,223,334', 'type 2', 1],
 ['Madrid', '\xa0•\xa0Urban', 'type 1', 1],
 ['Madrid', '6,345,000 (2019)[3]', 'type 2', 1],
 ['Dublin', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Dublin', '117.8\xa0km2 (45.5\xa0sq\xa0mi)', 'type 2', 1],
 ['Dublin', '\xa0•\xa0Urban', 'type 1', 1],
 ['Dublin', '318\xa0km2 (123\xa0sq\xa0mi)', 'type 2', 1],
 ['Dublin', 'Population\xa0(2016)', 'type 1', 1],
 ['Dublin', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Dublin', '554,554[3]', 'type 2', 1],
 ['Dublin', '\xa0•\xa0Urban', 'type 1', 1],
 ['Dublin', '1,173,179[7]', 'type 2', 1],
 ['Brussels', 'Population\xa0(1 January 2019)[4]', 'type 1', 1],
 ['Brussels', '1,208,542', 'type 2', 1],
 ['Zurich', 'Population\xa0(2018-12-31)[3][4]', 'type 1', 1],
 ['Zurich', '415,215', 'type 2', 1],
 ['Warsaw', '\xa0•\xa0Capital city and county', 'type 1', 1],
 ['Warsaw', '517.24\xa0km2 (199.71\xa0sq\xa0mi)', 'type 2', 1],
 ['Warsaw', 'Population\xa0(30 June 2020)', 'type 1', 1],
 ['Warsaw', '\xa0•\xa0Capital city and county', 'type 1', 1],
 ['Warsaw', '1,793,579 (1st) [1]', 'type 2', 1],
 ['Budapest', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Budapest', '525.2\xa0km2 (202.8\xa0sq\xa0mi)', 'type 2', 1],
 ['Budapest', '\xa0•\xa0Urban', 'type 1', 1],
 ['Budapest', '2,538\xa0km2 (980\xa0sq\xa0mi)', 'type 2', 1],
 ['Budapest', 'Population\xa0(2017)[7][8]', 'type 1', 1],
 ['Budapest', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Budapest', '1,752,286[1]', 'type 2', 1],
 ['Budapest', '\xa0•\xa0Urban', 'type 1', 1],
 ['Budapest', '2,997,958[5]', 'type 2', 1],
 ['Copenhagen', '\xa0•\xa0Urban', 'type 1', 1],
 ['Copenhagen', '292.5\xa0km2 (112.9\xa0sq\xa0mi)', 'type 2', 1],
 ['Copenhagen', 'Population\xa0(1 January 2020)[3]', 'type 1', 1],
 ['Copenhagen', '632,340', 'type 2', 1],
 ['Copenhagen', '\xa0•\xa0Urban', 'type 1', 1],
 ['Copenhagen', '1,330,993', 'type 2', 1],
 ['Copenhagen', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Copenhagen', '4,600/km2 (12,000/sq\xa0mi)', 'type 2', 1],
 ['Amsterdam', 'Population', 'type 1', 1],
 ['Amsterdam', '\xa0•\xa0Urban', 'type 1', 1],
 ['Amsterdam', '1,558,755', 'type 2', 1],
 ['Lyon', '\xa0•\xa0Urban\xa0(2017)', 'type 1', 1],
 ['Lyon', '1,171.1\xa0km2 (452.2\xa0sq\xa0mi)', 'type 2', 1],
 ['Lyon', 'Population\xa0(Jan.\xa02017)[2]', 'type 1', 1],
 ['Lyon', '516,092', 'type 2', 1],
 ['Lyon', '\xa0•\xa0Urban\xa0(2017[3])', 'type 1', 1],
 ['Lyon', '1,659,001', 'type 2', 1],
 ['Lyon', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Lyon', '1,400/km2 (3,700/sq\xa0mi)', 'type 2', 1],
 ['Hamburg', 'Population\xa0(30 June 2020)[2]', 'type 1', 1],
 ['Hamburg', '1,845,229', 'type 2', 1],
 ['Hamburg', '\xa0•\xa0Urban', 'type 1', 1],
 ['Hamburg', '2,484,800[1]', 'type 2', 1],
 ['Lisbon', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Lisbon', '100.05\xa0km2 (38.63\xa0sq\xa0mi)', 'type 2', 1],
 ['Lisbon', '\xa0•\xa0Urban', 'type 1', 1],
 ['Lisbon', '1,376\xa0km2 (531\xa0sq\xa0mi)', 'type 2', 1],
 ['Lisbon', 'Population\xa0(2017)', 'type 1', 1],
 ['Lisbon', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Lisbon', '505,526[1]', 'type 2', 1],
 ['Lisbon', '\xa0•\xa0Urban', 'type 1', 1],
 ['Lisbon', '2,042,477[3]', 'type 2', 1],
 ['Prague', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Prague', '496\xa0km2 (192\xa0sq\xa0mi)', 'type 2', 1],
 ['Prague', '\xa0•\xa0Urban', 'type 1', 1],
 ['Prague', '298\xa0km2 (115\xa0sq\xa0mi)', 'type 2', 1],
 ['Prague', 'Population\xa0(2020-01-01[5])', 'type 1', 1],
 ['Prague', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Prague', '1,324,277', 'type 2', 1],
 ['Oslo', '\xa0•\xa0Capital city, county and municipality', 'type 1', 1],
 ['Oslo', '480.75\xa0km2 (185.62\xa0sq\xa0mi)', 'type 2', 1],
 ['Oslo', 'Population\xa0(23 November 2020)[2][3][4]', 'type 1', 1],
 ['Oslo', '\xa0•\xa0Capital city, county and municipality', 'type 1', 1],
 ['Oslo', '634,293 ', 'type 2', 1],
 ['Oslo', '\xa0•\xa0Urban', 'type 1', 1],
 ['Oslo', '1,019,513', 'type 2', 1],
 ['Helsinki', 'Capital city', 'type 1', 1],
 ['Helsinki', '8 April 1812', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Helsinki', '715.48\xa0km2 (276.25\xa0sq\xa0mi)', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Urban', 'type 1', 1],
 ['Helsinki', '680.12\xa0km2 (262.60\xa0sq\xa0mi)', 'type 2', 1],
 ['Helsinki', 'Population\xa0(2020-12-31)[3]', 'type 1', 1],
 ['Helsinki', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Helsinki', '657,674', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Urban', 'type 1', 1],
 ['Helsinki', '1,268,296', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Helsinki', '1,900/km2 (4,800/sq\xa0mi)', 'type 2', 1],
 ['Helsinki', 'Population by native language[4]', 'type 1', 1],
 ['Helsinki', '84.3% (official)', 'type 2', 1],
 ['Helsinki', 'Population by age[5]', 'type 1', 1],
 ['Helsinki', '13.7%', 'type 2', 1],
 ['Edinburgh', '\xa0•\xa0Capital city and council area', 'type 1', 1],
 ['Edinburgh', '264\xa0km2 (102\xa0sq\xa0mi)', 'type 2', 1],
 ['Edinburgh', '\xa0•\xa0Urban', 'type 1', 1],
 ['Edinburgh', '119\xa0km2 (46\xa0sq\xa0mi)', 'type 2', 1],
 ['Edinburgh', 'Population\xa0(mid-2016\xa0est.)', 'type 1', 1],
 ['Edinburgh', '\xa0•\xa0Capital city and council area', 'type 1', 1],
 ['Edinburgh', '488,050 (City)[1]518,500 (Council area)[2]', 'type 2', 1],
 ['Edinburgh', '\xa0•\xa0Urban', 'type 1', 1],
 ['Edinburgh', '512,150[1]', 'type 2', 1],
 ['Geneva', 'Population\xa0(2018-12-31)[2]', 'type 1', 1],
 ['Geneva', '201,818', 'type 2', 1],
 ['Ljubljana', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Ljubljana', '163.8\xa0km2 (63.2\xa0sq\xa0mi)', 'type 2', 1],
 ['Ljubljana', 'Population\xa0(2020)[3]', 'type 1', 1],
 ['Ljubljana', '\xa0•\xa0Capital city', 'type 1', 1],
 ['Ljubljana', ' 295,504', 'type 2', 1],
 ['Athens', '\xa0•\xa0Urban', 'type 1', 1],
 ['Athens', '412\xa0km2 (159\xa0sq\xa0mi)', 'type 2', 1],
 ['Athens', 'Population\xa0(2012)[2]', 'type 1', 1],
 ['Athens', '664,046', 'type 2', 1],
 ['Athens', '\xa0•\xa0Urban', 'type 1', 1],
 ['Athens', '3,090,508', 'type 2', 1],
 ['Athens', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Athens', '7,500/km2 (19,000/sq\xa0mi)', 'type 2', 1],
 ['Luxembourg', 'Population\xa0(2021)', 'type 1', 1],
 ['Luxembourg', '124,528', 'type 2', 1],
 ['Krakow', 'Population\xa0(31 December 2019)', 'type 1', 1],
 ['Krakow', '779,115  (2nd)[1]', 'type 2', 1]]

Составим словарь, ключами которого будет являться город, а значениями- его население:

In [8]:

for element in parse_list:
    if (not('km2'in element[1]))and(not('Urban' in element[1]))and(not('%') in element[1])and(not(' by ') in element[1]):
        population_dict[element[0]] = element[1]
population_dict

{'Paris': '10,785,092',
 'Stockholm': '1,605,030',
 'London': '9,787,426',
 'Berlin': '4,473,100',
 'Munich': '2,606,021',
 'Oporto': '287,591',
 'Milan': '1,399,860',
 'Bratislava': '563,682',
 'Vienna': '1,911,191 (01−01−20)',
 'Rome': '4,342,212[2]',
 'Barcelona': '4,840,000[3]',
 'Madrid': '6,345,000 (2019)[3]',
 'Dublin': '1,173,179[7]',
 'Brussels': '1,208,542',
 'Zurich': '415,215',
 'Warsaw': '1,793,579 (1st) [1]',
 'Budapest': '2,997,958[5]',
 'Copenhagen': '1,330,993',
 'Amsterdam': '1,558,755',
 'Lyon': '1,659,001',
 'Hamburg': '2,484,800[1]',
 'Lisbon': '2,042,477[3]',
 'Prague': '1,324,277',
 'Oslo': '1,019,513',
 'Helsinki': '1,268,296',
 'Edinburgh': '512,150[1]',
 'Geneva': '201,818',
 'Ljubljana': ' 295,504',
 'Athens': '3,090,508',
 'Luxembourg': '124,528',
 'Krakow': '779,115  (2nd)[1]'}

Необходимо почистить данные по населению:

In [9]:
import re

In [10]:
for city,population in population_dict.items():
    population_dict[city]= (re.findall('((\d+\,{0,1}){1,3})',str(population)))[0][0]                      
for city,population in population_dict.items():
    population_dict[city]= int(population.replace(',',''))
population_dict

{'Paris': 10785092,
 'Stockholm': 1605030,
 'London': 9787426,
 'Berlin': 4473100,
 'Munich': 2606021,
 'Oporto': 287591,
 'Milan': 1399860,
 'Bratislava': 563682,
 'Vienna': 1911191,
 'Rome': 4342212,
 'Barcelona': 4840000,
 'Madrid': 6345000,
 'Dublin': 1173179,
 'Brussels': 1208542,
 'Zurich': 415215,
 'Warsaw': 1793579,
 'Budapest': 2997958,
 'Copenhagen': 1330993,
 'Amsterdam': 1558755,
 'Lyon': 1659001,
 'Hamburg': 2484800,
 'Lisbon': 2042477,
 'Prague': 1324277,
 'Oslo': 1019513,
 'Helsinki': 1268296,
 'Edinburgh': 512150,
 'Geneva': 201818,
 'Ljubljana': 295504,
 'Athens': 3090508,
 'Luxembourg': 124528,
 'Krakow': 779115}

In [11]:
i = 0
k = 0
parse_list_d = list()
for rows in rows_list:
    for row in rows:
        cells1 = row.findChildren('th')
        cells2 = row.findChildren('td')
        for cell in cells1:
            value1 = cell.text
            if ('density' in value1.lower())and(not('metro' in value1.lower())):
                k = 1
                parse_list_d.append([city_list[i],value1,'type 1',k])
            
        for cell in cells2:
            if k>0:
                value2 = cell.text
                parse_list_d.append([city_list[i],value2,'type 2',k])
                k += -1
    i += 1
parse_list_d

[['Paris', '\xa0•\xa0Density', 'type 1', 1],
 ['Paris', '21,000/km2 (53,000/sq\xa0mi)', 'type 2', 1],
 ['Paris', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Paris', '3,800/km2 (9,800/sq\xa0mi)', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Density', 'type 1', 1],
 ['Stockholm', '5,200/km2 (13,000/sq\xa0mi)', 'type 2', 1],
 ['Stockholm', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Stockholm', '4,200/km2 (11,000/sq\xa0mi)', 'type 2', 1],
 ['London', '\xa0•\xa0Density', 'type 1', 1],
 ['London', '5,666/km2 (14,670/sq\xa0mi)', 'type 2', 1],
 ['Munich', '\xa0•\xa0Density', 'type 1', 1],
 ['Munich', '4,800/km2 (12,000/sq\xa0mi)', 'type 2', 1],
 ['Oporto', '\xa0•\xa0Density', 'type 1', 1],
 ['Oporto', '6,900/km2 (18,000/sq\xa0mi)', 'type 2', 1],
 ['Milan', '\xa0•\xa0Density', 'type 1', 1],
 ['Milan', '7,700/km2 (20,000/sq\xa0mi)', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Density', 'type 1', 1],
 ['Bratislava', '1,200/km2 (3,100/sq\xa0mi)', 'type 2', 1],
 ['Bratislava', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Bratislava', '661/km2 (1,710/sq\xa0mi)', 'type 2', 1],
 ['Vienna', '\xa0•\xa0Density', 'type 1', 1],
 ['Vienna', '4,326.1/km2 (11,205/sq\xa0mi)', 'type 2', 1],
 ['Rome', '\xa0•\xa0Density', 'type 1', 1],
 ['Rome', '2,236/km2 (5,790/sq\xa0mi)', 'type 2', 1],
 ['Barcelona', '\xa0•\xa0Density', 'type 1', 1],
 ['Barcelona', '16,000/km2 (41,000/sq\xa0mi)', 'type 2', 1],
 ['Madrid', '\xa0•\xa0Density', 'type 1', 1],
 ['Madrid', '5,300/km2 (14,000/sq\xa0mi)', 'type 2', 1],
 ['Dublin', '\xa0•\xa0Density', 'type 1', 1],
 ['Dublin', '4,811/km2 (12,460/sq\xa0mi)', 'type 2', 1],
 ['Brussels', '\xa0•\xa0Density', 'type 1', 1],
 ['Brussels', '7,400/km2 (19,000/sq\xa0mi)', 'type 2', 1],
 ['Zurich', '\xa0•\xa0Density', 'type 1', 1],
 ['Zurich', '4,700/km2 (12,000/sq\xa0mi)', 'type 2', 1],
 ['Warsaw', '\xa0•\xa0Density', 'type 1', 1],
 ['Warsaw', '3,460/km2 (9,000/sq\xa0mi)', 'type 2', 1],
 ['Budapest', '\xa0•\xa0Density', 'type 1', 1],
 ['Budapest', '3,388/km2 (8,770/sq\xa0mi)', 'type 2', 1],
 ['Copenhagen', '\xa0•\xa0Density', 'type 1', 1],
 ['Copenhagen', '3,500/km2 (9,100/sq\xa0mi)', 'type 2', 1],
 ['Copenhagen', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Copenhagen', '4,600/km2 (12,000/sq\xa0mi)', 'type 2', 1],
 ['Lyon', '\xa0•\xa0Density', 'type 1', 1],
 ['Lyon', '11,000/km2 (28,000/sq\xa0mi)', 'type 2', 1],
 ['Lyon', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Lyon', '1,400/km2 (3,700/sq\xa0mi)', 'type 2', 1],
 ['Hamburg', '\xa0•\xa0Density', 'type 1', 1],
 ['Hamburg', '2,400/km2 (6,300/sq\xa0mi)', 'type 2', 1],
 ['Prague', '\xa0•\xa0Density', 'type 1', 1],
 ['Prague', '2,700/km2 (6,900/sq\xa0mi)', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Density', 'type 1', 1],
 ['Helsinki', '3,076.84/km2 (7,969.0/sq\xa0mi)', 'type 2', 1],
 ['Helsinki', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Helsinki', '1,900/km2 (4,800/sq\xa0mi)', 'type 2', 1],
 ['Edinburgh', '\xa0•\xa0Density', 'type 1', 1],
 ['Edinburgh', '1,828/km2 (4,730/sq\xa0mi)', 'type 2', 1],
 ['Geneva', '\xa0•\xa0Density', 'type 1', 1],
 ['Geneva', '13,000/km2 (33,000/sq\xa0mi)', 'type 2', 1],
 ['Ljubljana', '\xa0•\xa0Density', 'type 1', 1],
 ['Ljubljana', '1,712/km2 (4,430/sq\xa0mi)', 'type 2', 1],
 ['Athens', '\xa0•\xa0Urban\xa0density', 'type 1', 1],
 ['Athens', '7,500/km2 (19,000/sq\xa0mi)', 'type 2', 1],
 ['Luxembourg', '\xa0•\xa0Density', 'type 1', 1],
 ['Luxembourg', '2,400/km2 (6,300/sq\xa0mi)', 'type 2', 1],
 ['Luxembourg', '\xa0•\xa0Density\xa0rank', 'type 1', 1],
 ['Luxembourg', '2nd of 102', 'type 2', 1],
 ['Krakow', '\xa0•\xa0Density', 'type 1', 1],
 ['Krakow', '2,359/km2 (6,110/sq\xa0mi)', 'type 2', 1]]

In [12]:
for element in parse_list_d:
    if ('km2'in element[1]):
        density_dict[element[0]] = element[1]
density_dict

{'Paris': '3,800/km2 (9,800/sq\xa0mi)',
 'Stockholm': '4,200/km2 (11,000/sq\xa0mi)',
 'London': '5,666/km2 (14,670/sq\xa0mi)',
 'Berlin': 0,
 'Munich': '4,800/km2 (12,000/sq\xa0mi)',
 'Oporto': '6,900/km2 (18,000/sq\xa0mi)',
 'Milan': '7,700/km2 (20,000/sq\xa0mi)',
 'Bratislava': '661/km2 (1,710/sq\xa0mi)',
 'Vienna': '4,326.1/km2 (11,205/sq\xa0mi)',
 'Rome': '2,236/km2 (5,790/sq\xa0mi)',
 'Barcelona': '16,000/km2 (41,000/sq\xa0mi)',
 'Madrid': '5,300/km2 (14,000/sq\xa0mi)',
 'Dublin': '4,811/km2 (12,460/sq\xa0mi)',
 'Brussels': '7,400/km2 (19,000/sq\xa0mi)',
 'Zurich': '4,700/km2 (12,000/sq\xa0mi)',
 'Warsaw': '3,460/km2 (9,000/sq\xa0mi)',
 'Budapest': '3,388/km2 (8,770/sq\xa0mi)',
 'Copenhagen': '4,600/km2 (12,000/sq\xa0mi)',
 'Amsterdam': 0,
 'Lyon': '1,400/km2 (3,700/sq\xa0mi)',
 'Hamburg': '2,400/km2 (6,300/sq\xa0mi)',
 'Lisbon': 0,
 'Prague': '2,700/km2 (6,900/sq\xa0mi)',
 'Oslo': 0,
 'Helsinki': '1,900/km2 (4,800/sq\xa0mi)',
 'Edinburgh': '1,828/km2 (4,730/sq\xa0mi)',
 'Geneva': '13,000/km2 (33,000/sq\xa0mi)',
 'Ljubljana': '1,712/km2 (4,430/sq\xa0mi)',
 'Athens': '7,500/km2 (19,000/sq\xa0mi)',
 'Luxembourg': '2,400/km2 (6,300/sq\xa0mi)',
 'Krakow': '2,359/km2 (6,110/sq\xa0mi)'}

In [13]:
for city,population in density_dict.items():
    density_dict[city]= (re.findall('((\d+\,{0,1}){1,3})',str(population)))[0][0]                      

for city,population in density_dict.items():
    density_dict[city]= int(population.replace(',',''))
density_dict

{'Paris': 3800,
 'Stockholm': 4200,
 'London': 5666,
 'Berlin': 0,
 'Munich': 4800,
 'Oporto': 6900,
 'Milan': 7700,
 'Bratislava': 661,
 'Vienna': 4326,
 'Rome': 2236,
 'Barcelona': 16000,
 'Madrid': 5300,
 'Dublin': 4811,
 'Brussels': 7400,
 'Zurich': 4700,
 'Warsaw': 3460,
 'Budapest': 3388,
 'Copenhagen': 4600,
 'Amsterdam': 0,
 'Lyon': 1400,
 'Hamburg': 2400,
 'Lisbon': 0,
 'Prague': 2700,
 'Oslo': 0,
 'Helsinki': 1900,
 'Edinburgh': 1828,
 'Geneva': 13000,
 'Ljubljana': 1712,
 'Athens': 7500,
 'Luxembourg': 2400,
 'Krakow': 2359}

Ещё на предыдущем шаге было видно, что для ряда городов не удалось извлечь плотность населения. Просмотр соответствующих страниц показывает, что эти данные там просто отсутствуют.
Попробуем  рассчитать их и исправить

In [14]:
i = 0
k = 0
parse_list_a = list()
for rows in rows_list:
    for row in rows:
        cells1 = row.findChildren('th')
        cells2 = row.findChildren('td')
        for cell in cells1:
            value1 = cell.text
            if ('area' in value1.lower()):
                k = 1
                parse_list_a.append([city_list[i],value1,'type 1',k])
            
        for cell in cells2:
            value2 = cell.text
            if k>0 and ('km2' in value2.lower()):
                value2 = cell.text
                parse_list_a.append([city_list[i],value2,'type 2',k])
                k += -1
    i += 1
parse_list_a

[['Paris', 'Area1', 'type 1', 1],
 ['Paris', '105.4\xa0km2 (40.7\xa0sq\xa0mi)', 'type 2', 1],
 ['Stockholm', 'Area[2]', 'type 1', 1],
 ['Stockholm', '188\xa0km2 (73\xa0sq\xa0mi)', 'type 2', 1],
 ['Stockholm', 'Area code(s)', 'type 1', 1],
 ['London', 'Area', 'type 1', 1],
 ['London', '1,572\xa0km2 (607\xa0sq\xa0mi)', 'type 2', 1],
 ['London', 'Postcode areas', 'type 1', 1],
 ['London', 'Area codes', 'type 1', 1],
 ['Berlin', 'Area[1]', 'type 1', 1],
 ['Berlin', '891.7\xa0km2 (344.3\xa0sq\xa0mi)', 'type 2', 1],
 ['Berlin', 'Area code(s)', 'type 1', 1],
 ['Munich', 'Area', 'type 1', 1],
 ['Munich', '310.43\xa0km2 (119.86\xa0sq\xa0mi)', 'type 2', 1],
 ['Oporto', 'Area', 'type 1', 1],
 ['Oporto', '41.42\xa0km2 (15.99\xa0sq\xa0mi)', 'type 2', 1],
 ['Oporto', 'Area code(s)', 'type 1', 1],
 ['Milan', 'Area', 'type 1', 1],
 ['Milan', '181.76\xa0km2 (70.18\xa0sq\xa0mi)', 'type 2', 1],
 ['Milan', 'Area code(s)', 'type 1', 1],
 ['Bratislava', 'Area', 'type 1', 1],
 ['Bratislava', '367.584\xa0km2 (141.925\xa0sq\xa0mi)', 'type 2', 1],
 ['Bratislava', 'Area code(s)', 'type 1', 1],
 ['Vienna', 'Area[1]', 'type 1', 1],
 ['Vienna', '414.78\xa0km2 (160.15\xa0sq\xa0mi)', 'type 2', 1],
 ['Rome', 'Area', 'type 1', 1],
 ['Rome', '1,285\xa0km2 (496.3\xa0sq\xa0mi)', 'type 2', 1],
 ['Rome', 'Area code(s)', 'type 1', 1],
 ['Rome', 'Area', 'type 1', 1],
 ['Rome', 'Area', 'type 1', 1],
 ['Barcelona', 'Area[2]', 'type 1', 1],
 ['Barcelona', '101.4\xa0km2 (39.2\xa0sq\xa0mi)', 'type 2', 1],
 ['Barcelona', 'Area code', 'type 1', 1],
 ['Madrid', 'Area', 'type 1', 1],
 ['Madrid', '604.31\xa0km2 (233.33\xa0sq\xa0mi)', 'type 2', 1],
 ['Madrid', 'Area code(s)', 'type 1', 1],
 ['Dublin', 'Area[4][5]', 'type 1', 1],
 ['Dublin', '117.8\xa0km2 (45.5\xa0sq\xa0mi)', 'type 2', 1],
 ['Dublin', 'Area code(s)', 'type 1', 1],
 ['Brussels', 'Area[3]', 'type 1', 1],
 ['Brussels', '162.4\xa0km2 (62.7\xa0sq\xa0mi)', 'type 2', 1],
 ['Brussels', 'Area code(s)', 'type 1', 1],
 ['Zurich', 'Area[1][2]', 'type 1', 1],
 ['Zurich', '87.88\xa0km2 (33.93\xa0sq\xa0mi)', 'type 2', 1],
 ['Warsaw', 'Area', 'type 1', 1],
 ['Warsaw', '517.24\xa0km2 (199.71\xa0sq\xa0mi)', 'type 2', 1],
 ['Warsaw', 'Area code(s)', 'type 1', 1],
 ['Budapest', 'Area[3]', 'type 1', 1],
 ['Budapest', '525.2\xa0km2 (202.8\xa0sq\xa0mi)', 'type 2', 1],
 ['Budapest', 'Area code', 'type 1', 1],
 ['Budapest', 'Area', 'type 1', 1],
 ['Budapest', 'Area', 'type 1', 1],
 ['Copenhagen', 'Area[1][2]', 'type 1', 1],
 ['Copenhagen', '179.8\xa0km2 (69.4\xa0sq\xa0mi)', 'type 2', 1],
 ['Copenhagen', 'Area code(s)', 'type 1', 1],
 ['Amsterdam', 'Area[2][3]', 'type 1', 1],
 ['Amsterdam', '219.32\xa0km2 (84.68\xa0sq\xa0mi)', 'type 2', 1],
 ['Amsterdam', 'Area code', 'type 1', 1],
 ['Lyon', 'Area1', 'type 1', 1],
 ['Lyon', '47.87\xa0km2 (18.48\xa0sq\xa0mi)', 'type 2', 1],
 ['Hamburg', 'Area', 'type 1', 1],
 ['Hamburg', '755.22\xa0km2 (291.59\xa0sq\xa0mi)', 'type 2', 1],
 ['Hamburg', 'Area code(s)', 'type 1', 1],
 ['Lisbon', 'Area', 'type 1', 1],
 ['Lisbon', '100.05\xa0km2 (38.63\xa0sq\xa0mi)', 'type 2', 1],
 ['Lisbon', 'Area code(s)', 'type 1', 1],
 ['Prague', 'Area[3]', 'type 1', 1],
 ['Prague', '496\xa0km2 (192\xa0sq\xa0mi)', 'type 2', 1],
 ['Oslo', 'Area[1]', 'type 1', 1],
 ['Oslo', '480.75\xa0km2 (185.62\xa0sq\xa0mi)', 'type 2', 1],
 ['Helsinki', 'Area\xa0(2018-01-01)[2]', 'type 1', 1],
 ['Helsinki', '715.48\xa0km2 (276.25\xa0sq\xa0mi)', 'type 2', 1],
 ['Helsinki', 'Area rank', 'type 1', 1],
 ['Helsinki', '3,076.84/km2 (7,969.0/sq\xa0mi)', 'type 2', 1],
 ['Helsinki', 'Area code(s)', 'type 1', 1],
 ['Edinburgh', 'Council area', 'type 1', 1],
 ['Edinburgh', 'Lieutenancy area', 'type 1', 1],
 ['Edinburgh', 'Area', 'type 1', 1],
 ['Edinburgh', '\xa0•\xa0Capital city and council area', 'type 1', 1],
 ['Edinburgh', '264\xa0km2 (102\xa0sq\xa0mi)', 'type 2', 1],
 ['Edinburgh', '\xa0•\xa0Capital city and council area', 'type 1', 1],
 ['Edinburgh', '1,828/km2 (4,730/sq\xa0mi)', 'type 2', 1],
 ['Edinburgh', 'Postcode areas', 'type 1', 1],
 ['Edinburgh', 'Area code(s)', 'type 1', 1],
 ['Edinburgh', 'UKM25', 'type 2', 1],
 ['Geneva', 'Area[1]', 'type 1', 1],
 ['Geneva', '15.92\xa0km2 (6.15\xa0sq\xa0mi)', 'type 2', 1],
 ['Ljubljana', 'Area', 'type 1', 1],
 ['Ljubljana', '163.8\xa0km2 (63.2\xa0sq\xa0mi)', 'type 2', 1],
 ['Ljubljana', 'Area code(s)', 'type 1', 1],
 ['Athens', 'Area', 'type 1', 1],
 ['Athens', '38.964\xa0km2 (15.044\xa0sq\xa0mi)', 'type 2', 1],
 ['Luxembourg', 'Area', 'type 1', 1],
 ['Luxembourg', '51.46\xa0km2 (19.87\xa0sq\xa0mi)', 'type 2', 1],
 ['Luxembourg', 'Area rank', 'type 1', 1],
 ['Luxembourg', '2,400/km2 (6,300/sq\xa0mi)', 'type 2', 1],
 ['Krakow', 'Area', 'type 1', 1],
 ['Krakow', '326.8\xa0km2 (126.2\xa0sq\xa0mi)', 'type 2', 1],
 ['Krakow', 'Area code(s)', 'type 1', 1]]

In [15]:
for element in parse_list_a:
    if ('km2'in element[1]):
        area_dict[element[0]] = element[1]
area_dict

{'Paris': '105.4\xa0km2 (40.7\xa0sq\xa0mi)',
 'Stockholm': '188\xa0km2 (73\xa0sq\xa0mi)',
 'London': '1,572\xa0km2 (607\xa0sq\xa0mi)',
 'Berlin': '891.7\xa0km2 (344.3\xa0sq\xa0mi)',
 'Munich': '310.43\xa0km2 (119.86\xa0sq\xa0mi)',
 'Oporto': '41.42\xa0km2 (15.99\xa0sq\xa0mi)',
 'Milan': '181.76\xa0km2 (70.18\xa0sq\xa0mi)',
 'Bratislava': '367.584\xa0km2 (141.925\xa0sq\xa0mi)',
 'Vienna': '414.78\xa0km2 (160.15\xa0sq\xa0mi)',
 'Rome': '1,285\xa0km2 (496.3\xa0sq\xa0mi)',
 'Barcelona': '101.4\xa0km2 (39.2\xa0sq\xa0mi)',
 'Madrid': '604.31\xa0km2 (233.33\xa0sq\xa0mi)',
 'Dublin': '117.8\xa0km2 (45.5\xa0sq\xa0mi)',
 'Brussels': '162.4\xa0km2 (62.7\xa0sq\xa0mi)',
 'Zurich': '87.88\xa0km2 (33.93\xa0sq\xa0mi)',
 'Warsaw': '517.24\xa0km2 (199.71\xa0sq\xa0mi)',
 'Budapest': '525.2\xa0km2 (202.8\xa0sq\xa0mi)',
 'Copenhagen': '179.8\xa0km2 (69.4\xa0sq\xa0mi)',
 'Amsterdam': '219.32\xa0km2 (84.68\xa0sq\xa0mi)',
 'Lyon': '47.87\xa0km2 (18.48\xa0sq\xa0mi)',
 'Hamburg': '755.22\xa0km2 (291.59\xa0sq\xa0mi)',
 'Lisbon': '100.05\xa0km2 (38.63\xa0sq\xa0mi)',
 'Prague': '496\xa0km2 (192\xa0sq\xa0mi)',
 'Oslo': '480.75\xa0km2 (185.62\xa0sq\xa0mi)',
 'Helsinki': '3,076.84/km2 (7,969.0/sq\xa0mi)',
 'Edinburgh': '1,828/km2 (4,730/sq\xa0mi)',
 'Geneva': '15.92\xa0km2 (6.15\xa0sq\xa0mi)',
 'Ljubljana': '163.8\xa0km2 (63.2\xa0sq\xa0mi)',
 'Athens': '38.964\xa0km2 (15.044\xa0sq\xa0mi)',
 'Luxembourg': '2,400/km2 (6,300/sq\xa0mi)',
 'Krakow': '326.8\xa0km2 (126.2\xa0sq\xa0mi)'}

In [16]:
for city,population in area_dict.items():
    area_dict[city]= (re.findall('((\d+\,{0,1}){1,3})',str(population)))[0][0]                      

for city,population in area_dict.items():
    area_dict[city]= int(population.replace(',',''))
area_dict

{'Paris': 105,
 'Stockholm': 188,
 'London': 1572,
 'Berlin': 891,
 'Munich': 310,
 'Oporto': 41,
 'Milan': 181,
 'Bratislava': 367,
 'Vienna': 414,
 'Rome': 1285,
 'Barcelona': 101,
 'Madrid': 604,
 'Dublin': 117,
 'Brussels': 162,
 'Zurich': 87,
 'Warsaw': 517,
 'Budapest': 525,
 'Copenhagen': 179,
 'Amsterdam': 219,
 'Lyon': 47,
 'Hamburg': 755,
 'Lisbon': 100,
 'Prague': 496,
 'Oslo': 480,
 'Helsinki': 3076,
 'Edinburgh': 1828,
 'Geneva': 15,
 'Ljubljana': 163,
 'Athens': 38,
 'Luxembourg': 2400,
 'Krakow': 326}

In [17]:
density_dict

{'Paris': 3800,
 'Stockholm': 4200,
 'London': 5666,
 'Berlin': 0,
 'Munich': 4800,
 'Oporto': 6900,
 'Milan': 7700,
 'Bratislava': 661,
 'Vienna': 4326,
 'Rome': 2236,
 'Barcelona': 16000,
 'Madrid': 5300,
 'Dublin': 4811,
 'Brussels': 7400,
 'Zurich': 4700,
 'Warsaw': 3460,
 'Budapest': 3388,
 'Copenhagen': 4600,
 'Amsterdam': 0,
 'Lyon': 1400,
 'Hamburg': 2400,
 'Lisbon': 0,
 'Prague': 2700,
 'Oslo': 0,
 'Helsinki': 1900,
 'Edinburgh': 1828,
 'Geneva': 13000,
 'Ljubljana': 1712,
 'Athens': 7500,
 'Luxembourg': 2400,
 'Krakow': 2359}

In [18]:
population_dict

{'Paris': 10785092,
 'Stockholm': 1605030,
 'London': 9787426,
 'Berlin': 4473100,
 'Munich': 2606021,
 'Oporto': 287591,
 'Milan': 1399860,
 'Bratislava': 563682,
 'Vienna': 1911191,
 'Rome': 4342212,
 'Barcelona': 4840000,
 'Madrid': 6345000,
 'Dublin': 1173179,
 'Brussels': 1208542,
 'Zurich': 415215,
 'Warsaw': 1793579,
 'Budapest': 2997958,
 'Copenhagen': 1330993,
 'Amsterdam': 1558755,
 'Lyon': 1659001,
 'Hamburg': 2484800,
 'Lisbon': 2042477,
 'Prague': 1324277,
 'Oslo': 1019513,
 'Helsinki': 1268296,
 'Edinburgh': 512150,
 'Geneva': 201818,
 'Ljubljana': 295504,
 'Athens': 3090508,
 'Luxembourg': 124528,
 'Krakow': 779115}

In [19]:
for city,density in density_dict.items():
    if density == 0:
        density_dict[city] = round(population_dict[city]/area_dict[city])
density_dict

{'Paris': 3800,
 'Stockholm': 4200,
 'London': 5666,
 'Berlin': 5020,
 'Munich': 4800,
 'Oporto': 6900,
 'Milan': 7700,
 'Bratislava': 661,
 'Vienna': 4326,
 'Rome': 2236,
 'Barcelona': 16000,
 'Madrid': 5300,
 'Dublin': 4811,
 'Brussels': 7400,
 'Zurich': 4700,
 'Warsaw': 3460,
 'Budapest': 3388,
 'Copenhagen': 4600,
 'Amsterdam': 7118,
 'Lyon': 1400,
 'Hamburg': 2400,
 'Lisbon': 20425,
 'Prague': 2700,
 'Oslo': 2124,
 'Helsinki': 1900,
 'Edinburgh': 1828,
 'Geneva': 13000,
 'Ljubljana': 1712,
 'Athens': 7500,
 'Luxembourg': 2400,
 'Krakow': 2359}

In [20]:
import pandas as pd

In [29]:
combined_dict = dict()
for element in city_dict.keys():
    combined_dict[element] = [population_dict[element],area_dict[element],density_dict[element]]
city_df = pd.DataFrame.from_dict(combined_dict,orient = 'index',columns=['population','area','density'])
city_df

            population  area  density
Paris         10785092   105     3800
Stockholm      1605030   188     4200
London         9787426  1572     5666
Berlin         4473100   891     5020
Munich         2606021   310     4800
Oporto          287591    41     6900
Milan          1399860   181     7700
Bratislava      563682   367      661
Vienna         1911191   414     4326
Rome           4342212  1285     2236
Barcelona      4840000   101    16000
Madrid         6345000   604     5300
Dublin         1173179   117     4811
Brussels       1208542   162     7400
Zurich          415215    87     4700
Warsaw         1793579   517     3460
Budapest       2997958   525     3388
Copenhagen     1330993   179     4600
Amsterdam      1558755   219     7118
Lyon           1659001    47     1400
Hamburg        2484800   755     2400
Lisbon         2042477   100    20425
Prague         1324277   496     2700
Oslo           1019513   480     2124
Helsinki       1268296  3076     1900
Edinburgh       512150  1828     1828
Geneva          201818    15    13000
Ljubljana       295504   163     1712
Athens         3090508    38     7500
Luxembourg      124528  2400     2400
Krakow          779115   326     2359

In [30]:
city_df.to_csv('parse_data.csv')